### ISSUE TITLE
bypass failed !

### ISSUE THREAD

**Issue by sparta34** [decoder-it/powershellveryless#2]
first thanks for this project but , windows defender stop this attack

**Comment by decoder-it** [comment]
you should post more info, too generic... anyway try to integrate it with this new AMSI bypass https://github.com/rasta-mouse/AmsiScanBufferBypass/blob/master/ASBBypass/Program.cs

**Comment by 0xVIC** [comment]
Hello, Win Defender detects both.

**Comment by decoder-it** [comment]
Yes, with the lastest definitions. But it's very easy to bypass them again, just tested it. I won't publish any other updates, it's up to you to modify the source code ;-)
